version: '3.8'

services:
  voice-activity-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    command: python app/main.py

  voice-activity-frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - voice-activity-api
    environment:
      - PYTHONPATH=/app
    command: streamlit run frontend/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./frontend:/app/frontend

networks:
  default:
    name: voice-activity-network
